/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import administradores.AdministradorPrincipal;
import datos.Constantes;
import datos.Persona;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Registro extends javax.swing.JFrame {

    private String rutaFoto = "";
    private boolean isSesionIniciada = false;
    private String correoActual = "";

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        modificarRegistro();
    }

    private void modificarRegistro() {
        ChangeListener changeListener = new ChangeListener() {
            public void stateChanged(ChangeEvent changeEvent) {
                JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
                if (sourceTabbedPane.equals(jTabbedPaneOpciones)) {
                    int index = sourceTabbedPane.getSelectedIndex();
                    System.out.println("Tab changed to: " + sourceTabbedPane.getTitleAt(index));
                    if (sourceTabbedPane.getTitleAt(index).equals("Perfil") && isSesionIniciada == false) {
                        JOptionPane.showMessageDialog(null,
                                "Primero debe iniciar sesión",
                                "información", JOptionPane.ERROR_MESSAGE);
                        sourceTabbedPane.setSelectedIndex(Constantes.PAGINA_LOGIN);
                    } else if (sourceTabbedPane.getTitleAt(index).equals("Perfil Amigos") && isSesionIniciada == false) {
                        JOptionPane.showMessageDialog(null,
                                "Primero debe iniciar sesión",
                                "información", JOptionPane.ERROR_MESSAGE);
                        sourceTabbedPane.setSelectedIndex(Constantes.PAGINA_LOGIN);
                    }
                }
            }
        };
        jTabbedPaneOpciones.addChangeListener(changeListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneOpciones = new javax.swing.JTabbedPane();
        jLayeredPaneRegistro = new javax.swing.JLayeredPane();
        jLabelRegistroNombre = new javax.swing.JLabel();
        jTextFieldRegistroNombre = new javax.swing.JTextField();
        jLabelRegistroEdad = new javax.swing.JLabel();
        jTextFieldRegistroEdad = new javax.swing.JTextField();
        jLabelRegistroCarrera = new javax.swing.JLabel();
        jTextFieldRegistroCarrera = new javax.swing.JTextField();
        jLabelRegistroYearCarrera = new javax.swing.JLabel();
        jTextFieldRegistroYearCarrera = new javax.swing.JTextField();
        jLabelRegistroDireccion = new javax.swing.JLabel();
        jTextFieldRegistroDireccion = new javax.swing.JTextField();
        jLabelRegistroTelefono = new javax.swing.JLabel();
        jTextFieldRegistroTelefono = new javax.swing.JTextField();
        jLabelRegistroCorreo = new javax.swing.JLabel();
        jTextFieldRegistroCorreo = new javax.swing.JTextField();
        jLabelRegistroFoto = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelFondoRegistro = new javax.swing.JLabel();
        jLayeredPaneLogin = new javax.swing.JLayeredPane();
        jLabelLoginCorreo = new javax.swing.JLabel();
        jTextFieldLoginCorreo = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jLabelFondoLogin = new javax.swing.JLabel();
        jLayeredPanePerfil = new javax.swing.JLayeredPane();
        jLabelPerfilNombreCampo = new javax.swing.JLabel();
        jLabelPerfilEdadCampo = new javax.swing.JLabel();
        jLabelPerfilCarreraCampo = new javax.swing.JLabel();
        jLabelPerfilYearCarreraCampo = new javax.swing.JLabel();
        jLabelPerfilDireccionCampo = new javax.swing.JLabel();
        jLabelPerfilTelefonoCampo = new javax.swing.JLabel();
        jLabelPerfilCorreoCampo = new javax.swing.JLabel();
        jLabelFotoPerfil = new javax.swing.JLabel();
        jLabelPerfilNombre = new javax.swing.JLabel();
        jLabelPerfilEdad = new javax.swing.JLabel();
        jLabelPerfilCarrera = new javax.swing.JLabel();
        jLabelPerfilYearCarrera = new javax.swing.JLabel();
        jLabelPerfilDireccion = new javax.swing.JLabel();
        jLabelPerfilTelefono = new javax.swing.JLabel();
        jLabelPerfilCorreo = new javax.swing.JLabel();
        jLabelFondoPerfil = new javax.swing.JLabel();
        jLayeredPanePerfilAmigos = new javax.swing.JLayeredPane();
        jLabelPerfilNombreAmigoRegistrado = new javax.swing.JLabel();
        jComboBoxAmigosRegistrados = new javax.swing.JComboBox();
        jLabelPerfilNombreCampoAR = new javax.swing.JLabel();
        jLabelPerfilEdadCampoAR = new javax.swing.JLabel();
        jLabelPerfilCarreraCampo1AR = new javax.swing.JLabel();
        jLabelPerfilYearCarreraCampoAR = new javax.swing.JLabel();
        jLabelPerfilDireccionCampoAR = new javax.swing.JLabel();
        jLabelPerfilTelefonoCampoAR = new javax.swing.JLabel();
        jLabelPerfilCorreoCampoAR = new javax.swing.JLabel();
        jLabelFotoPerfil1 = new javax.swing.JLabel();
        jLabelPerfilNombre1 = new javax.swing.JLabel();
        jLabelPerfilEdad1 = new javax.swing.JLabel();
        jLabelPerfilCarrera1 = new javax.swing.JLabel();
        jLabelPerfilYearCarrera1 = new javax.swing.JLabel();
        jLabelPerfilDireccion1 = new javax.swing.JLabel();
        jLabelPerfilTelefono1 = new javax.swing.JLabel();
        jLabelPerfilCorreo1 = new javax.swing.JLabel();
        jLabelFondoPerfilAmigosRegistrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneOpciones.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPaneOpciones.setOpaque(true);

        jLayeredPaneRegistro.setBackground(new java.awt.Color(87, 240, 164));
        jLayeredPaneRegistro.setOpaque(true);
        jLayeredPaneRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistroNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroNombre.setText("Nombre");
        jLabelRegistroNombre.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneRegistro.add(jLabelRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 37));

        jTextFieldRegistroNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroNombre.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneRegistro.add(jTextFieldRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 30));

        jLabelRegistroEdad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroEdad.setText("Edad");
        jLabelRegistroEdad.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneRegistro.add(jLabelRegistroEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 37));

        jTextFieldRegistroEdad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroEdad.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneRegistro.add(jTextFieldRegistroEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 40));

        jLabelRegistroCarrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroCarrera.setText("Carrera");
        jLabelRegistroCarrera.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneRegistro.add(jLabelRegistroCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 37));

        jTextFieldRegistroCarrera.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroCarrera.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneRegistro.add(jTextFieldRegistroCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, 40));

        jLabelRegistroYearCarrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroYearCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroYearCarrera.setText("Año carrera");
        jLabelRegistroYearCarrera.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneRegistro.add(jLabelRegistroYearCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 37));

        jTextFieldRegistroYearCarrera.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroYearCarrera.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneRegistro.add(jTextFieldRegistroYearCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, 40));

        jLabelRegistroDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroDireccion.setText("Dirección");
        jLabelRegistroDireccion.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneRegistro.add(jLabelRegistroDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 37));

        jTextFieldRegistroDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroDireccion.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneRegistro.add(jTextFieldRegistroDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 37));

        jLabelRegistroTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroTelefono.setText("Telefóno");
        jLabelRegistroTelefono.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneRegistro.add(jLabelRegistroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 37));

        jTextFieldRegistroTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroTelefono.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneRegistro.add(jTextFieldRegistroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 130, 37));

        jLabelRegistroCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroCorreo.setText("Correo");
        jLabelRegistroCorreo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneRegistro.add(jLabelRegistroCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 37));

        jTextFieldRegistroCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroCorreo.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneRegistro.add(jTextFieldRegistroCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 130, 37));

        jLabelRegistroFoto.setBackground(new java.awt.Color(0, 0, 0));
        jLabelRegistroFoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroFoto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistroFoto.setText("Agregar Foto");
        jLabelRegistroFoto.setOpaque(true);
        jLabelRegistroFoto.setPreferredSize(new java.awt.Dimension(100, 14));
        jLabelRegistroFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelRegistroFotoMouseReleased(evt);
            }
        });
        jLayeredPaneRegistro.add(jLabelRegistroFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, 37));

        jLabelFoto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto.setOpaque(true);
        jLayeredPaneRegistro.add(jLabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 150, 140));

        jButtonRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("Registarse");
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jLayeredPaneRegistro.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 160, 30));

        jLabelFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jLayeredPaneRegistro.add(jLabelFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        jTabbedPaneOpciones.addTab("Registro", jLayeredPaneRegistro);

        jLayeredPaneLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLoginCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoginCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginCorreo.setText("Correo");
        jLabelLoginCorreo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPaneLogin.add(jLabelLoginCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jTextFieldLoginCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldLoginCorreo.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPaneLogin.add(jTextFieldLoginCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, 30));

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Ingresar");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jLayeredPaneLogin.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabelFondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jLayeredPaneLogin.add(jLabelFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPaneOpciones.addTab("Login", jLayeredPaneLogin);

        jLayeredPanePerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPerfilNombreCampo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilNombreCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilNombreCampo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilNombreCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 37));

        jLabelPerfilEdadCampo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilEdadCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilEdadCampo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilEdadCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, 37));

        jLabelPerfilCarreraCampo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCarreraCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCarreraCampo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilCarreraCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 37));

        jLabelPerfilYearCarreraCampo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilYearCarreraCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilYearCarreraCampo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilYearCarreraCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 37));

        jLabelPerfilDireccionCampo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilDireccionCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilDireccionCampo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilDireccionCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 310, 37));

        jLabelPerfilTelefonoCampo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilTelefonoCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilTelefonoCampo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilTelefonoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, 37));

        jLabelPerfilCorreoCampo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCorreoCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCorreoCampo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilCorreoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 300, 37));

        jLabelFotoPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFotoPerfil.setOpaque(true);
        jLayeredPanePerfil.add(jLabelFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 150, 140));

        jLabelPerfilNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilNombre.setText("Nombre");
        jLabelPerfilNombre.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 37));

        jLabelPerfilEdad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilEdad.setText("Edad");
        jLabelPerfilEdad.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 37));

        jLabelPerfilCarrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCarrera.setText("Carrera");
        jLabelPerfilCarrera.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 37));

        jLabelPerfilYearCarrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilYearCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilYearCarrera.setText("Año carrera");
        jLabelPerfilYearCarrera.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilYearCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 37));

        jLabelPerfilDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilDireccion.setText("Dirección");
        jLabelPerfilDireccion.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 37));

        jLabelPerfilTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilTelefono.setText("Telefóno");
        jLabelPerfilTelefono.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 37));

        jLabelPerfilCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCorreo.setText("Correo");
        jLabelPerfilCorreo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfil.add(jLabelPerfilCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 37));

        jLabelFondoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jLayeredPanePerfil.add(jLabelFondoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPaneOpciones.addTab("Perfil", jLayeredPanePerfil);

        jLayeredPanePerfilAmigos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPerfilNombreAmigoRegistrado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilNombreAmigoRegistrado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilNombreAmigoRegistrado.setText("Amigos");
        jLabelPerfilNombreAmigoRegistrado.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilNombreAmigoRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 37));

        jComboBoxAmigosRegistrados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPanePerfilAmigos.add(jComboBoxAmigosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 320, -1));

        jLabelPerfilNombreCampoAR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilNombreCampoAR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilNombreCampoAR.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilNombreCampoAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 37));

        jLabelPerfilEdadCampoAR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilEdadCampoAR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilEdadCampoAR.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilEdadCampoAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, 37));

        jLabelPerfilCarreraCampo1AR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCarreraCampo1AR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCarreraCampo1AR.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilCarreraCampo1AR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 37));

        jLabelPerfilYearCarreraCampoAR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilYearCarreraCampoAR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilYearCarreraCampoAR.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilYearCarreraCampoAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 37));

        jLabelPerfilDireccionCampoAR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilDireccionCampoAR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilDireccionCampoAR.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilDireccionCampoAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 310, 37));

        jLabelPerfilTelefonoCampoAR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilTelefonoCampoAR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilTelefonoCampoAR.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilTelefonoCampoAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, 37));

        jLabelPerfilCorreoCampoAR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCorreoCampoAR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCorreoCampoAR.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilCorreoCampoAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 300, 37));

        jLabelFotoPerfil1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFotoPerfil1.setOpaque(true);
        jLayeredPanePerfilAmigos.add(jLabelFotoPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 150, 140));

        jLabelPerfilNombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilNombre1.setText("Nombre");
        jLabelPerfilNombre1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 37));

        jLabelPerfilEdad1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilEdad1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilEdad1.setText("Edad");
        jLabelPerfilEdad1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 37));

        jLabelPerfilCarrera1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCarrera1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCarrera1.setText("Carrera");
        jLabelPerfilCarrera1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 37));

        jLabelPerfilYearCarrera1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilYearCarrera1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilYearCarrera1.setText("Año carrera");
        jLabelPerfilYearCarrera1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilYearCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 37));

        jLabelPerfilDireccion1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilDireccion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilDireccion1.setText("Dirección");
        jLabelPerfilDireccion1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 37));

        jLabelPerfilTelefono1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilTelefono1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilTelefono1.setText("Telefóno");
        jLabelPerfilTelefono1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 37));

        jLabelPerfilCorreo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPerfilCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilCorreo1.setText("Correo");
        jLabelPerfilCorreo1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPanePerfilAmigos.add(jLabelPerfilCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 37));

        jLabelFondoPerfilAmigosRegistrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jLayeredPanePerfilAmigos.add(jLabelFondoPerfilAmigosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPaneOpciones.addTab("Perfil Amigos", jLayeredPanePerfilAmigos);

        getContentPane().add(jTabbedPaneOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 415));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        boolean camposValidos = veficarCampos();
        if (!camposValidos) {
            JOptionPane.showMessageDialog(null,
                    "Verfique que todos los datos se hayan ingresado",
                    "información", JOptionPane.ERROR_MESSAGE);
        } else {

            String correo = jTextFieldRegistroCorreo.getText().trim();

            boolean existePersona = AdministradorPrincipal.getInstance().existePersona(correo);

            if (existePersona == false) {
                String nombre = jTextFieldRegistroNombre.getText().trim();
                String edad = jTextFieldRegistroEdad.getText().trim();
                String carrera = jTextFieldRegistroCarrera.getText().trim();
                String anoCarrera = jTextFieldRegistroYearCarrera.getText().trim();
                String direccion = jTextFieldRegistroDireccion.getText().trim();
                String telefono = jTextFieldRegistroTelefono.getText().trim();

                AdministradorPrincipal.getInstance().insertarUsuario(nombre, edad, carrera, anoCarrera, direccion, telefono, correo, rutaFoto);

                JOptionPane.showMessageDialog(null,
                        "Se ha registrado exitosamente",
                        "información", JOptionPane.INFORMATION_MESSAGE);

                jTabbedPaneOpciones.setSelectedIndex(Constantes.PAGINA_LOGIN);

            } else {
                JOptionPane.showMessageDialog(null,
                        "El correo debe ser único",
                        "información", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void actualizarFotoRegistro(String rutaFoto) {
        //Convierte la imagen
        ImageIcon foto = new ImageIcon(rutaFoto);
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(150,
                140, Image.SCALE_SMOOTH));

        //Asigna la imagen
        jLabelFoto.setIcon(icono);
    }

    private void actualizarFotoPerfil(String rutaFoto) {
        //Convierte la imagen
        ImageIcon foto = new ImageIcon(rutaFoto);
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(150,
                140, Image.SCALE_SMOOTH));

        //Asigna la imagen
        jLabelFotoPerfil.setIcon(icono);
    }

    private void jLabelRegistroFotoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroFotoMouseReleased
        //Crea un objeto de dialogo JFileChooser
        JFileChooser elemento = new JFileChooser();

        //Formatos de los iconos
        elemento.setFileFilter(new FileNameExtensionFilter("Archivo PNG", "png"));
        elemento.setFileFilter(new FileNameExtensionFilter("Archivo JPG", "jpg"));

        //Variable que va a buscar la foto y almacenar la direccion
        int option = elemento.showOpenDialog(this);

        //Valida si se seleccionó alguna imagen
        if (option == JFileChooser.APPROVE_OPTION) {
            try {
                //Obtener ruta y nombre al hacer click
                String file = elemento.getSelectedFile().getPath();
                rutaFoto = file;
                actualizarFotoRegistro(rutaFoto);

            } catch (Exception ex) {
            }
        }

        this.repaint();
    }//GEN-LAST:event_jLabelRegistroFotoMouseReleased

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if (isSesionIniciada == false) {
            correoActual = jTextFieldLoginCorreo.getText().trim();
            if (!correoActual.isEmpty()) {
                boolean existePersona = AdministradorPrincipal.getInstance().existePersona(correoActual);
                if (existePersona) {
                    JOptionPane.showMessageDialog(null,
                            "Bienvenid@",
                            "información", JOptionPane.INFORMATION_MESSAGE);
                    isSesionIniciada = true;
                    actualizarPerfil(correoActual);
                    jTabbedPaneOpciones.setSelectedIndex(Constantes.PAGINA_PERFIL);

                } else {
                    JOptionPane.showMessageDialog(null,
                            "Usuario no registrado",
                            "información", JOptionPane.ERROR_MESSAGE);
                    jTabbedPaneOpciones.setSelectedIndex(Constantes.PAGINA_REGISTRO);
                }
            }

        } else {
            actualizarPerfil(correoActual);
            jTabbedPaneOpciones.setSelectedIndex(Constantes.PAGINA_PERFIL);

        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void actualizarPerfil(String correo) {
        Persona persona = AdministradorPrincipal.getInstance().getPersona(correo);
        jLabelPerfilNombreCampo.setText(persona.getNombre());
        jLabelPerfilEdadCampo.setText(persona.getEdad());
        jLabelPerfilCarreraCampo.setText(persona.getCarrera());
        jLabelPerfilYearCarreraCampo.setText(persona.getAnoCarrera());
        jLabelPerfilTelefonoCampo.setText(persona.getTelefono());
        jLabelPerfilCorreoCampo.setText(persona.getCorreo());
        jLabelPerfilDireccionCampo.setText(persona.getDireccion());

        actualizarFotoPerfil(persona.getRutaFoto());
    }

    public boolean veficarCampos() {
        boolean resultado = false;
        String nombre = jTextFieldRegistroNombre.getText().trim();
        String edad = jTextFieldRegistroEdad.getText().trim();
        String carrera = jTextFieldRegistroCarrera.getText().trim();
        String anoCarrera = jTextFieldRegistroYearCarrera.getText().trim();
        String direccion = jTextFieldRegistroDireccion.getText().trim();
        String telefono = jTextFieldRegistroTelefono.getText().trim();
        String correo = jTextFieldRegistroCorreo.getText().trim();
        if (!nombre.isEmpty() && !edad.isEmpty() && !carrera.isEmpty()
                && !anoCarrera.isEmpty() && !direccion.isEmpty()
                && !telefono.isEmpty() && !correo.isEmpty() && !rutaFoto.isEmpty()) {
            resultado = true;
        }
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox jComboBoxAmigosRegistrados;
    private javax.swing.JLabel jLabelFondoLogin;
    private javax.swing.JLabel jLabelFondoPerfil;
    private javax.swing.JLabel jLabelFondoPerfilAmigosRegistrados;
    private javax.swing.JLabel jLabelFondoRegistro;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelFotoPerfil;
    private javax.swing.JLabel jLabelFotoPerfil1;
    private javax.swing.JLabel jLabelLoginCorreo;
    private javax.swing.JLabel jLabelPerfilCarrera;
    private javax.swing.JLabel jLabelPerfilCarrera1;
    private javax.swing.JLabel jLabelPerfilCarreraCampo;
    private javax.swing.JLabel jLabelPerfilCarreraCampo1AR;
    private javax.swing.JLabel jLabelPerfilCorreo;
    private javax.swing.JLabel jLabelPerfilCorreo1;
    private javax.swing.JLabel jLabelPerfilCorreoCampo;
    private javax.swing.JLabel jLabelPerfilCorreoCampoAR;
    private javax.swing.JLabel jLabelPerfilDireccion;
    private javax.swing.JLabel jLabelPerfilDireccion1;
    private javax.swing.JLabel jLabelPerfilDireccionCampo;
    private javax.swing.JLabel jLabelPerfilDireccionCampoAR;
    private javax.swing.JLabel jLabelPerfilEdad;
    private javax.swing.JLabel jLabelPerfilEdad1;
    private javax.swing.JLabel jLabelPerfilEdadCampo;
    private javax.swing.JLabel jLabelPerfilEdadCampoAR;
    private javax.swing.JLabel jLabelPerfilNombre;
    private javax.swing.JLabel jLabelPerfilNombre1;
    private javax.swing.JLabel jLabelPerfilNombreAmigoRegistrado;
    private javax.swing.JLabel jLabelPerfilNombreCampo;
    private javax.swing.JLabel jLabelPerfilNombreCampoAR;
    private javax.swing.JLabel jLabelPerfilTelefono;
    private javax.swing.JLabel jLabelPerfilTelefono1;
    private javax.swing.JLabel jLabelPerfilTelefonoCampo;
    private javax.swing.JLabel jLabelPerfilTelefonoCampoAR;
    private javax.swing.JLabel jLabelPerfilYearCarrera;
    private javax.swing.JLabel jLabelPerfilYearCarrera1;
    private javax.swing.JLabel jLabelPerfilYearCarreraCampo;
    private javax.swing.JLabel jLabelPerfilYearCarreraCampoAR;
    private javax.swing.JLabel jLabelRegistroCarrera;
    private javax.swing.JLabel jLabelRegistroCorreo;
    private javax.swing.JLabel jLabelRegistroDireccion;
    private javax.swing.JLabel jLabelRegistroEdad;
    private javax.swing.JLabel jLabelRegistroFoto;
    private javax.swing.JLabel jLabelRegistroNombre;
    private javax.swing.JLabel jLabelRegistroTelefono;
    private javax.swing.JLabel jLabelRegistroYearCarrera;
    private javax.swing.JLayeredPane jLayeredPaneLogin;
    private javax.swing.JLayeredPane jLayeredPanePerfil;
    private javax.swing.JLayeredPane jLayeredPanePerfilAmigos;
    private javax.swing.JLayeredPane jLayeredPaneRegistro;
    private javax.swing.JTabbedPane jTabbedPaneOpciones;
    private javax.swing.JTextField jTextFieldLoginCorreo;
    private javax.swing.JTextField jTextFieldRegistroCarrera;
    private javax.swing.JTextField jTextFieldRegistroCorreo;
    private javax.swing.JTextField jTextFieldRegistroDireccion;
    private javax.swing.JTextField jTextFieldRegistroEdad;
    private javax.swing.JTextField jTextFieldRegistroNombre;
    private javax.swing.JTextField jTextFieldRegistroTelefono;
    private javax.swing.JTextField jTextFieldRegistroYearCarrera;
    // End of variables declaration//GEN-END:variables
}
