/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import administradores.AdministradorPrincipal;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author RUBEN
 */
public class Registro extends javax.swing.JFrame {

    private String rutaFoto = "";

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelRegistroNombre = new javax.swing.JLabel();
        jTextFieldRegistroNombre = new javax.swing.JTextField();
        jLabelRegistroEdad = new javax.swing.JLabel();
        jTextFieldRegistroEdad = new javax.swing.JTextField();
        jLabelRegistroCarrera = new javax.swing.JLabel();
        jTextFieldRegistroCarrera = new javax.swing.JTextField();
        jLabelRegistroYearCarrera = new javax.swing.JLabel();
        jTextFieldRegistroYearCarrera = new javax.swing.JTextField();
        jLabelRegistroDireccion = new javax.swing.JLabel();
        jTextFieldRegistroDireccion = new javax.swing.JTextField();
        jLabelRegistroTelefono = new javax.swing.JLabel();
        jTextFieldRegistroTelefono = new javax.swing.JTextField();
        jLabelRegistroCorreo = new javax.swing.JLabel();
        jTextFieldRegistroCorreo = new javax.swing.JTextField();
        jLabelRegistroFoto = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelFondoRegistro = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabelRegistroNombre1 = new javax.swing.JLabel();
        jLabelRegistroEdad1 = new javax.swing.JLabel();
        jLabelRegistroCarrera1 = new javax.swing.JLabel();
        jLabelRegistroYearCarrera1 = new javax.swing.JLabel();
        jLabelRegistroDireccion1 = new javax.swing.JLabel();
        jLabelRegistroTelefono1 = new javax.swing.JLabel();
        jLabelFondoRegistro1 = new javax.swing.JLabel();
        jLabelRegistroCorreo1 = new javax.swing.JLabel();
        jLabelRegistroNombre2 = new javax.swing.JLabel();
        jLabelRegistroEdad2 = new javax.swing.JLabel();
        jLabelRegistroCarrera2 = new javax.swing.JLabel();
        jLabelRegistroYearCarrera2 = new javax.swing.JLabel();
        jLabelRegistroDireccion2 = new javax.swing.JLabel();
        jLabelRegistroTelefono2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setOpaque(true);

        jLayeredPane1.setBackground(new java.awt.Color(87, 240, 164));
        jLayeredPane1.setOpaque(true);

        jLabelRegistroNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroNombre.setText("Nombre");
        jLabelRegistroNombre.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane1.add(jLabelRegistroNombre);
        jLabelRegistroNombre.setBounds(20, 30, 80, 37);

        jTextFieldRegistroNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroNombre.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPane1.add(jTextFieldRegistroNombre);
        jTextFieldRegistroNombre.setBounds(140, 30, 130, 30);

        jLabelRegistroEdad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroEdad.setText("Edad");
        jLabelRegistroEdad.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane1.add(jLabelRegistroEdad);
        jLabelRegistroEdad.setBounds(20, 80, 80, 37);

        jTextFieldRegistroEdad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroEdad.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPane1.add(jTextFieldRegistroEdad);
        jTextFieldRegistroEdad.setBounds(140, 70, 130, 40);

        jLabelRegistroCarrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroCarrera.setText("Carrera");
        jLabelRegistroCarrera.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane1.add(jLabelRegistroCarrera);
        jLabelRegistroCarrera.setBounds(20, 130, 80, 37);

        jTextFieldRegistroCarrera.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroCarrera.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPane1.add(jTextFieldRegistroCarrera);
        jTextFieldRegistroCarrera.setBounds(140, 120, 130, 40);

        jLabelRegistroYearCarrera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroYearCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroYearCarrera.setText("Año carrera");
        jLabelRegistroYearCarrera.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane1.add(jLabelRegistroYearCarrera);
        jLabelRegistroYearCarrera.setBounds(20, 180, 120, 37);

        jTextFieldRegistroYearCarrera.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroYearCarrera.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPane1.add(jTextFieldRegistroYearCarrera);
        jTextFieldRegistroYearCarrera.setBounds(140, 170, 130, 40);

        jLabelRegistroDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroDireccion.setText("Dirección");
        jLabelRegistroDireccion.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane1.add(jLabelRegistroDireccion);
        jLabelRegistroDireccion.setBounds(20, 230, 80, 37);

        jTextFieldRegistroDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroDireccion.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPane1.add(jTextFieldRegistroDireccion);
        jTextFieldRegistroDireccion.setBounds(140, 220, 130, 37);

        jLabelRegistroTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroTelefono.setText("Telefóno");
        jLabelRegistroTelefono.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane1.add(jLabelRegistroTelefono);
        jLabelRegistroTelefono.setBounds(20, 280, 80, 37);

        jTextFieldRegistroTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroTelefono.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPane1.add(jTextFieldRegistroTelefono);
        jTextFieldRegistroTelefono.setBounds(140, 270, 130, 37);

        jLabelRegistroCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroCorreo.setText("Correo");
        jLabelRegistroCorreo.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane1.add(jLabelRegistroCorreo);
        jLabelRegistroCorreo.setBounds(20, 330, 80, 37);

        jTextFieldRegistroCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRegistroCorreo.setPreferredSize(new java.awt.Dimension(150, 20));
        jLayeredPane1.add(jTextFieldRegistroCorreo);
        jTextFieldRegistroCorreo.setBounds(140, 320, 130, 37);

        jLabelRegistroFoto.setBackground(new java.awt.Color(0, 0, 0));
        jLabelRegistroFoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroFoto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistroFoto.setText("Agregar Foto");
        jLabelRegistroFoto.setOpaque(true);
        jLabelRegistroFoto.setPreferredSize(new java.awt.Dimension(100, 14));
        jLabelRegistroFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelRegistroFotoMouseReleased(evt);
            }
        });
        jLayeredPane1.add(jLabelRegistroFoto);
        jLabelRegistroFoto.setBounds(290, 180, 150, 37);

        jLabelFoto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto.setOpaque(true);
        jLayeredPane1.add(jLabelFoto);
        jLabelFoto.setBounds(290, 30, 150, 140);

        jButtonRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("Registarse");
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonRegistrar);
        jButtonRegistrar.setBounds(280, 320, 160, 30);

        jLabelFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jLayeredPane1.add(jLabelFondoRegistro);
        jLabelFondoRegistro.setBounds(0, 0, 460, 390);

        jTabbedPane1.addTab("Registro", jLayeredPane1);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistroNombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroNombre1.setText("Nombre");
        jLabelRegistroNombre1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 37));

        jLabelRegistroEdad1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroEdad1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroEdad1.setText("Edad");
        jLabelRegistroEdad1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 37));

        jLabelRegistroCarrera1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroCarrera1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroCarrera1.setText("Carrera");
        jLabelRegistroCarrera1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 37));

        jLabelRegistroYearCarrera1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroYearCarrera1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroYearCarrera1.setText("Año carrera");
        jLabelRegistroYearCarrera1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroYearCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 37));

        jLabelRegistroDireccion1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroDireccion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroDireccion1.setText("Dirección");
        jLabelRegistroDireccion1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 37));

        jLabelRegistroTelefono1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroTelefono1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroTelefono1.setText("Telefóno");
        jLabelRegistroTelefono1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 37));

        jLabelFondoRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jLayeredPane2.add(jLabelFondoRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelRegistroCorreo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroCorreo1.setText("Correo");
        jLabelRegistroCorreo1.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 223, 427, 37));

        jLabelRegistroNombre2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroNombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroNombre2.setText("Nombre");
        jLabelRegistroNombre2.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 37));

        jLabelRegistroEdad2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroEdad2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroEdad2.setText("Edad");
        jLabelRegistroEdad2.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroEdad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 37));

        jLabelRegistroCarrera2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroCarrera2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroCarrera2.setText("Carrera");
        jLabelRegistroCarrera2.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroCarrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, 37));

        jLabelRegistroYearCarrera2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroYearCarrera2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroYearCarrera2.setText("Año carrera");
        jLabelRegistroYearCarrera2.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroYearCarrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, 37));

        jLabelRegistroDireccion2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroDireccion2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroDireccion2.setText("Dirección");
        jLabelRegistroDireccion2.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, 37));

        jLabelRegistroTelefono2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegistroTelefono2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroTelefono2.setText("Telefóno");
        jLabelRegistroTelefono2.setPreferredSize(new java.awt.Dimension(100, 14));
        jLayeredPane2.add(jLabelRegistroTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 80, 37));

        jTabbedPane1.addTab("Perfil", jLayeredPane2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 415));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        boolean camposValidos = veficarCampos();
        if (!camposValidos) {
            JOptionPane.showMessageDialog(null,
                    "Verfique que todos los datos se hayan ingresado",
                    "información", JOptionPane.ERROR_MESSAGE);
        } else {

            String correo = jTextFieldRegistroCorreo.getText().trim();

            boolean existePersona = AdministradorPrincipal.getInstance().existePersona(correo);

            if (existePersona == false) {
                String nombre = jTextFieldRegistroNombre.getText().trim();
                String edad = jTextFieldRegistroEdad.getText().trim();
                String carrera = jTextFieldRegistroCarrera.getText().trim();
                String anoCarrera = jTextFieldRegistroYearCarrera.getText().trim();
                String direccion = jTextFieldRegistroDireccion.getText().trim();
                String telefono = jTextFieldRegistroTelefono.getText().trim();

                AdministradorPrincipal.getInstance().insertarUsuario(rutaFoto, nombre, edad, carrera, anoCarrera, direccion, telefono, correo);

                JOptionPane.showMessageDialog(null,
                        "Se ha registrado exitosamente",
                        "información", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null,
                        "El correo debe ser único",
                        "información", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jLabelRegistroFotoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroFotoMouseReleased
        //Crea un objeto de dialogo JFileChooser
        JFileChooser elemento = new JFileChooser();

        //Formatos de los iconos
        elemento.setFileFilter(new FileNameExtensionFilter("Archivo PNG", "png"));
        elemento.setFileFilter(new FileNameExtensionFilter("Archivo JPG", "jpg"));

        //Variable que va a buscar la foto y almacenar la direccion
        int option = elemento.showOpenDialog(this);

        //Valida si se seleccionó alguna imagen
        if (option == JFileChooser.APPROVE_OPTION) {
            try {
                //Obtener ruta y nombre al hacer click
                String file = elemento.getSelectedFile().getPath();
                rutaFoto = file;

                //Convierte la imagen
                ImageIcon foto = new ImageIcon(rutaFoto);
                Icon icono = new ImageIcon(foto.getImage().getScaledInstance(150,
                        140, Image.SCALE_SMOOTH));

                //Asigna la imagen
                jLabelFoto.setIcon(icono);

            } catch (Exception ex) {
            }
        }

        this.repaint();
    }//GEN-LAST:event_jLabelRegistroFotoMouseReleased

    public boolean veficarCampos() {
        boolean resultado = false;
        String nombre = jTextFieldRegistroNombre.getText().trim();
        String edad = jTextFieldRegistroEdad.getText().trim();
        String carrera = jTextFieldRegistroCarrera.getText().trim();
        String anoCarrera = jTextFieldRegistroYearCarrera.getText().trim();
        String direccion = jTextFieldRegistroDireccion.getText().trim();
        String telefono = jTextFieldRegistroTelefono.getText().trim();
        String correo = jTextFieldRegistroCorreo.getText().trim();
        if (!nombre.isEmpty() && !edad.isEmpty() && !carrera.isEmpty()
                && !anoCarrera.isEmpty() && !direccion.isEmpty()
                && !telefono.isEmpty() && !correo.isEmpty() && !rutaFoto.isEmpty()) {
            resultado = true;
        }
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelFondoRegistro;
    private javax.swing.JLabel jLabelFondoRegistro1;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelRegistroCarrera;
    private javax.swing.JLabel jLabelRegistroCarrera1;
    private javax.swing.JLabel jLabelRegistroCarrera2;
    private javax.swing.JLabel jLabelRegistroCorreo;
    private javax.swing.JLabel jLabelRegistroCorreo1;
    private javax.swing.JLabel jLabelRegistroDireccion;
    private javax.swing.JLabel jLabelRegistroDireccion1;
    private javax.swing.JLabel jLabelRegistroDireccion2;
    private javax.swing.JLabel jLabelRegistroEdad;
    private javax.swing.JLabel jLabelRegistroEdad1;
    private javax.swing.JLabel jLabelRegistroEdad2;
    private javax.swing.JLabel jLabelRegistroFoto;
    private javax.swing.JLabel jLabelRegistroNombre;
    private javax.swing.JLabel jLabelRegistroNombre1;
    private javax.swing.JLabel jLabelRegistroNombre2;
    private javax.swing.JLabel jLabelRegistroTelefono;
    private javax.swing.JLabel jLabelRegistroTelefono1;
    private javax.swing.JLabel jLabelRegistroTelefono2;
    private javax.swing.JLabel jLabelRegistroYearCarrera;
    private javax.swing.JLabel jLabelRegistroYearCarrera1;
    private javax.swing.JLabel jLabelRegistroYearCarrera2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldRegistroCarrera;
    private javax.swing.JTextField jTextFieldRegistroCorreo;
    private javax.swing.JTextField jTextFieldRegistroDireccion;
    private javax.swing.JTextField jTextFieldRegistroEdad;
    private javax.swing.JTextField jTextFieldRegistroNombre;
    private javax.swing.JTextField jTextFieldRegistroTelefono;
    private javax.swing.JTextField jTextFieldRegistroYearCarrera;
    // End of variables declaration//GEN-END:variables
}
